//fetch all users
export const FETCH_ALL_USERS_REQUEST="FECTH_ALL_USERS_REQUEST";
export const FETCH_ALL_USERS_SUCCESS="FECTH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILURE="FECTH_ALL_USERS_FAILURE";


// delete a user
export const DELETE_USER_REQUEST="DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE="DELETE_USER_FAILURE";


// update a user role
export const UPDATE_USER_REQUEST="UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE="UPDATE_USER_FAILURE";


// fetch all clients
export const FETCH_ALL_CLIENTS_REQUEST="FECTH_ALL_CLIENTS_REQUEST";
export const FETCH_ALL_CLIENTS_SUCCESS="FECTH_ALL_CLIENTS_SUCCESS";
export const FETCH_ALL_CLIENTS_FAILURE="FECTH_ALL_CLIENTS_FAILURE";