export const qBank = [
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "099099",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "093909",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "009039",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "090089",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "01010101",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "092299",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "099099",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "222099",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "2222099",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "09922099",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "222292099",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "0998999099",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "099099",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "099099",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "099099",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "09459099",
  },
  {
    question: "How build the app ?",
    answers: ["Vinayak", "Sarthak", "Somil", "Devesh"],
    correct: "Vinayak",
    questionId: "0912219099",
  },
];
